export const ROUTES = {
  All: "/",
  Chat: "/chat",
  ChatDetail: "/chat/:id",
  Quiz: "/quiz",
  QuizDetail: "/quiz/:id",
  QuizDetailStart: "/quiz/:id/start",
  QuizEdit: "/quiz/:id/edit",
  QuizCreate: "/quiz/create",
  Login: "/login",
  Register: "/register",
  Games: "/games",
  Cards: "/cards",
  CardsCreate: "/cards/create",
  CardDetail: "/cards/:id",
  CardEdit: "/cards/:id/edit",
}