export const ROUTES = {
  Home: "/home",
  All: "/",
  Chat: "/chat",
  ChatDetail: "/chat/:id",
  Quiz: "/quiz",
  QuizDetail: "/quiz/:id",
  QuizDetailStart: "/quiz/:id/start",
  QuizEdit: "/quiz/:id/edit",
  QuizCreate: "/quiz/create",
  Login: "/login",
  Register: "/register",
  ForgotPassword: "/forgot-password",
  Rewards: "/rewards",
  RewardsMy: "/rewards/my",
  Trainer: "/trainer",
  Leaderboard: "/leaderboard",
  Profile: "/profile",
  Cards: "/cards",
  CardsCreate: "/cards/create",
  CardDetail: "/cards/:id",
  CardEdit: "/cards/:id/edit",
  Assignments: "/assignments",
  AssignmentCreate: "/assignments/create",
  AssignmentDetail: "/assignments/:id",
  AssignmentEdit: "/assignments/:id/edit",
};
